//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Font_to_GCode.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>A</string>
  <string>B</string>
  <string>C</string>
  <string>D</string>
  <string>E</string>
  <string>F</string>
  <string>G</string>
  <string>H</string>
  <string>I</string>
  <string>J</string>
  <string>K</string>
  <string>L</string>
  <string>M</string>
  <string>N</string>
  <string>O</string>
  <string>P</string>
  <string>Q</string>
  <string>R</string>
  <string>S</string>
  <string>T</string>
  <string>U</string>
  <string>V</string>
  <string>W</string>
  <string>X</string>
  <string>Y</string>
  <string>Z</string>
  <string>-</string>
  <string>0</string>
  <string>1</string>
  <string>2</string>
  <string>3</string>
  <string>4</string>
  <string>5</string>
  <string>6</string>
  <string>7</string>
  <string>8</string>
  <string>9</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection CharacterList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CharacterList"]));
            }
            set {
                this["CharacterList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public string FontSize {
            get {
                return ((string)(this["FontSize"]));
            }
            set {
                this["FontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string GCodeHeight {
            get {
                return ((string)(this["GCodeHeight"]));
            }
            set {
                this["GCodeHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public string GCodeDepth {
            get {
                return ((string)(this["GCodeDepth"]));
            }
            set {
                this["GCodeDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9500")]
        public string GCodeProgram {
            get {
                return ((string)(this["GCodeProgram"]));
            }
            set {
                this["GCodeProgram"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G00 G17 G20 G40 G80 G90 G94")]
        public string GCodeInit {
            get {
                return ((string)(this["GCodeInit"]));
            }
            set {
                this["GCodeInit"] = value;
            }
        }
    }
}
